extension:
  taskExecution:
    "0":
      success: true
      timestamp: 1778218769030
    "1":
      success: true
      timestamp: 1778218769554
    "2":
      success: true
      timestamp: 1778218769990
    "3":
      success: true
      timestamp: 1778218770481
    "4":
      success: true
      timestamp: 1778218770978
    "5":
      success: true
      timestamp: 1778218771464
    "6":
      success: true
      timestamp: 1778218772275
    "7":
      success: true
      timestamp: 1778218772883
    "8":
      success: true
      timestamp: 1778218773319
